### ISSUE TITLE
Multiple calls

### ISSUE THREAD

**Issue by ognjen-petrovic** [Ricorocks-Digital-Agency/Soap#20]
```
$soap = Soap::to('https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL');

$response = $soap->call('NumberToWords', ['ubiNum' => 10]);
$this->info($response->NumberToWordsResult);

$response = $soap->call('NumberToWords', ['ubiNum' => 20]);
$this->info($response->NumberToWordsResult);
```
This code writes out:
ten
ten

I expected:
ten
twenty

Native SoapClient does not cache response ( it writes ten twenty ):

```
$soap = new \SoapClient('https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL');

$response = $soap->__soapCall('NumberToWords', [['ubiNum' => 10]]);
$this->info($response->NumberToWordsResult); // ten

$response = $soap->__soapCall('NumberToWords', [['ubiNum' => 20]]);
$this->info($response->NumberToWordsResult); //twenty
```

What are reasons to cache the response?

 I get expected, when I override the getResponse method, like this:
```
    protected function getResponse()
    {
//        return $this->response ??= $this->getRealResponse();
        return $this->getRealResponse();
    }
```

Is it safe to do that?

Thanks, Ognjen

**Comment by lukeraymonddowning** [comment]
Hi 👋🏼

The reason we cache the request is that each request should be isolated so that it can contain its own hooks, mocks and testing assertions. 

A simple way to refactor your code here would be to either move the `Soap::to()` call to its own function and return a new instance for each `call` method or alternatively create a macro for that endpoint:

```php
// Service Provider boot method
Soap::macro(
    'numberConversion', 
    fn() => $this->to('https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL')
);

// Implementation
$response = Soap::numberConversion->call('NumberToWords', ['ubiNum' => 10]);
$response = Soap::numberConversion->call('NumberToWords', ['ubiNum' => 20]);
```

Hope that helps. I'll close this issue for now, but please reopen if that hasn't answered your question.

**Comment by ognjen-petrovic** [comment]
Hi,

Thank you for the explanation.
I have to make several calls to same method in a row and I would like to avoid repeated wsdl loading...so will use native client for this one.

Regards

**Comment by lukeraymonddowning** [comment]
That is a fair point. I'll look into it today and see if there is a way we can allow multiple calls on a single WSDL.
