### ISSUE TITLE
Class soap does not exist

### ISSUE THREAD

**Issue by paulo-santos-ideahub** [Ricorocks-Digital-Agency/Soap#24]
I just got started using this and I'm not exactly sure what I did wrong. I installed it as per instructions but calling the facade gets me this error:
```
In Container.php line 838:

  Target class [soap] does not exist.


In Container.php line 836:

  Class soap does not exist
```
I tried running `composer dump-autoload` to rule out autoloading issues and it's still getting that error. At this point, I'm not sure what exactly I'm missing.

I'm using Lumen 8.0 with php 7.4 if it matters.

**Comment by lukeraymonddowning** [comment]
Looks like you haven't got the php soap extension installed. Install that, and it should work dandy.

**Comment by lukeraymonddowning** [comment]
I'm going to close this for now. Please re-open if your issue isn't solved.

**Comment by paulo-santos-ideahub** [comment]
I suspected as much and checked and it appears to be already installed. I manually installed it for good measure, yet this is still coming up.
