### ISSUE TITLE
Add support for php 7.x < 7.4

### ISSUE THREAD

**Issue by bedoz** [Ricorocks-Digital-Agency/Soap#25]
Hello everybody, can you add support for php < 7.4? i have now 7.3 and i can't use "fn() =>" format but it can be solved quickly.
Thank you

**Comment by lukeraymonddowning** [comment]
Hi @bedoz,

We're not going to be adding support for 7.3, because we really like the features offered by 7.4+ and other organisations building for Laravel (such as Spatie) have stopped supporting 7.3.

Apologies for the inconvenience.

Regards,
Luke
