### ISSUE TITLE
Class soap does not exist.

### ISSUE THREAD

**Issue by paulo-santos-ideahub** [Ricorocks-Digital-Agency/Soap#26]
Related to issue https://github.com/Ricorocks-Digital-Agency/Soap/issues/24

I've suspected this and already did the checking and I can confirm that the soap extension is loaded in phpinfo. Maybe this is related? I even rebooted the whole development server to be sure.

```
soap

Soap Client => enabled
Soap Server => enabled

Directive => Local Value => Master Value
soap.wsdl_cache => 1 => 1
soap.wsdl_cache_dir => /tmp => /tmp
soap.wsdl_cache_enabled => 1 => 1
soap.wsdl_cache_limit => 5 => 5
soap.wsdl_cache_ttl => 86400 => 86400
```

**Comment by ArthurPatriot** [comment]
@paulo-santos-ideahub run `php -m`. Are you see `soap` and `openssl` on list?

**Comment by paulo-santos-ideahub** [comment]
@ArthurPatriot Yes I do.

**Comment by nedwors** [comment]
@paulo-santos-ideahub, would you be able to post your code stripped down to the least loc that still cause this error? 

As a note, are you calling the Soap Facade in a register method of a ServiceProvider?

**Comment by paulo-santos-ideahub** [comment]
@nedwors , no I did not call the Soap Facade in the register method of a ServiceProvider. As for the least LoC:
```
use RicorocksDigitalAgency\Soap\Facades\Soap;

//snip
$header = Soap::header();
/*
->name('Authenticate')
->namespace($namespace)
->data([
    'params' => 'values'
])
->mustUnderstand();
*/
//snip
```

**Comment by ThadPinch** [comment]
I fixed this with:
1. uncomment extension=soap in php.ini 
2. apt-get install php-soap 
3. service apache2 restart

**Comment by paulo-santos-ideahub** [comment]
> I fixed this with:
> 
> 1. uncomment extension=soap in php.ini
> 2. apt-get install php-soap
> 3. service apache2 restart

Tried this and didn't help. Still the same issue.

**Comment by nedwors** [comment]
Hi @paulo-santos-ideahub, we are going to investigate further, thanks for you patience.

**Comment by rodrigoross** [comment]
It is already closed, but for those that encouter this issue when using Lumen, I added the SoapServiceProvider in the `bootstrap/app.php` file.

```
$app->register(\RicorocksDigitalAgency\Soap\Providers\SoapServiceProvider::class);
```

It worked correctly after.
