### ISSUE TITLE
Unresolvable dependency resolving [Parameter #3 [ <optional> $mustunderstand ]] in class SoapHeader

### ISSUE THREAD

**Issue by ArthurPatriot** [Ricorocks-Digital-Agency/Soap#27]
Laravel 8.46.0
PHP 7.4.18
Package 1.3.0

**Error** 1:  `Unresolvable dependency resolving [Parameter #3 [ <optional> $mustunderstand ]] in class SoapHeader {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #3 [ <optional> $mustunderstand ]] in class SoapHeader at /var/www/magnum/vendor/laravel/framework/src/Illuminate/Container/Container.php:1067)`
**Error 1 Quick Fix:** \ricorocks-digital-agency\soap\src\Request\SoapClientRequest.php:100 replace mustUnderstand to mustunderstand...

**Error 2:** Soap header throw error when `actor` is null...
**Error 2 Quick Fix:** Add actor to header

**Comment by nedwors** [comment]
@ArthurPatriot, could you please provide a sample of your code that you are seeing this fail on please?

**Comment by ArthurPatriot** [comment]
@nedwors 

And not working if not add actor...

![image](https://user-images.githubusercontent.com/36359548/122188654-d6430780-ce98-11eb-99a0-f4bb84d467db.png)

**Comment by nedwors** [comment]
@ArthurPatriot thank you for the snippet, very helpful. We are working on some fixes, would appreciate you testing the pr with your code when we publish, will ping you when ready.

**Comment by ArthurPatriot** [comment]
@nedwors sure, I will wait impatiently))

**Comment by nedwors** [comment]
@ArthurPatriot, have created a draft pr #28, would you be able to see how it performs in your code please?

**Comment by ArthurPatriot** [comment]
@nedwors checking...

**Comment by ArthurPatriot** [comment]
@nedwors checked. All Ok.

**Comment by nedwors** [comment]
> @nedwors checked. All Ok.

Brilliant, thank you. 

Your second point about actor, were you meaning this package's header class was throwing an error or the php SoapHeader class?

**Comment by ArthurPatriot** [comment]
Trouble in Laravel IoC, `resolve` helper function require `actor` field must be filled... when it`s `null` laravel throw exception... Current solution perfect exclude `actor` field from array to resolve)))

Error 2: `PHP Warning:  SoapHeader::SoapHeader(): Invalid actor in /var/www/***/vendor/laravel/framework/src/Illuminate/Container/Container.php`

**Comment by ArthurPatriot** [comment]
@nedwors  Recheck without actor... Still not working...

If not use `actor()` throw error: `Illuminate/Contracts/Container/BindingResolutionException with message 'Unresolvable dependency resolving [Parameter #4 [ <optional> $actor ]] in class SoapHeader`

![image](https://user-images.githubusercontent.com/36359548/122298104-00321380-cf05-11eb-811a-e95b0d8c9d7f.png)

![image](https://user-images.githubusercontent.com/36359548/122297938-ceb94800-cf04-11eb-90c0-5b87a4dffb14.png)

**Comment by ArthurPatriot** [comment]
@nedwors add fix in [PR #29 ](https://github.com/Ricorocks-Digital-Agency/Soap/pull/29)

**Comment by nedwors** [comment]
@ArthurPatriot appreciate the pr, not really keen on enforcing the soap constant for a null actor of we don't need to. Have pushed an update using the service container on the existing PR, this should solve the optional dependency resolution failure.

**Comment by ArthurPatriot** [comment]
@nedwors has other solution? actor field must be null (optional handling not working...) or soap const... Current solution with excluding actor from resolve array not working.

**Comment by ArthurPatriot** [comment]
@nedwors ok, it's one of solutions... If it's working let's create release))

**Comment by nedwors** [comment]
Can you recheck with the latest updates on pr #28 please for the actor issue @ArthurPatriot?

**Comment by ArthurPatriot** [comment]
@nedwors `PHP Warning:  SoapHeader::SoapHeader(): Invalid actor in /var/www/***/vendor/ricorocks-digital-agency/soap/src/Providers/SoapServiceProvider.php on line 35`

**Comment by ArthurPatriot** [comment]
May be solution in my PR is normal)))

**Comment by lukeraymonddowning** [comment]
@nedwors after looking into it a little further, isn't SOAP_ACTOR_NONE the equivalent of null anyway?

https://stackoverflow.com/questions/33543078/php-soap-client-invalid-actor/37185662#37185662

**Comment by ArthurPatriot** [comment]
@lukeraymonddowning my solution don't break any user code...) Tested in live code...

**Comment by nedwors** [comment]
Updated pr #28 @ArthurPatriot - be good to get your input. Thanks

**Comment by lukeraymonddowning** [comment]
Code merged into 1.3.1
