### ISSUE TITLE
Unexpected '=>' (T_DOUBLE_ARROW)

### ISSUE THREAD

**Issue by urmatt** [Ricorocks-Digital-Agency/Soap#33]
Hello, after install I got this error:

In SoapServiceProvider.php line 17:
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

Then I changed 
```
$this->app->singleton('soap', fn () => app(Soap::class));
```
to 

```
$this->app->singleton('soap', function () {
            app(Soap::class);
        });
```

This resolves issue but I. think only until I update composer

php -v

PHP 7.3.27 (cli) (built: Feb  4 2021 12:13:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group

php artisan --version
Laravel Framework 8.47.0

**Comment by lukeraymonddowning** [comment]
Hi @urmatt 

The minimum PHP version is 7.4, as we use shorthand functions throughout the codebase. @nedwors can we add a PHP requirement to the composer.json file?

**Comment by nedwors** [comment]
> Hi @urmatt 
> 
> 
> 
> The minimum PHP version is 7.4, as we use shorthand functions throughout the codebase. @nedwors can we add a PHP requirement to the composer.json file?

@lukeraymonddowning, of course. Why don't we include it on your Pest PR?
