### ISSUE TITLE
User .pem cert

### ISSUE THREAD

**Issue by afbravoh98** [Ricorocks-Digital-Agency/Soap#34]
Hi!
I am trying to consume a soap service sending a .pem certificate, but I receive a connection error with the endpoint indicating that the certificate is not sent. This is the correct way to attach it? 

```
 $response = Soap::to(env('SOAP_URL', ''))
            ->withBasicAuth('xxxx', 'C/.21k')
            ->withOptions([
                'local_cert' => storage_path() . '\certificate.pem',
                'soap_version' => SOAP_1_2
            ])
            ->trace(true)
            ->call('consultaPlano', $params);
```

**Comment by lukeraymonddowning** [comment]
Can't really help without more info. Can you try a request using the default soap client so we can be sure it's not an issue with your configuration?
