### ISSUE TITLE
Response body format 

### ISSUE THREAD

**Issue by agnulakmirak** [Ricorocks-Digital-Agency/Soap#41]
What is the format of the response from a basic soap request? 

```php
    $response = Soap::to('url')->call('method', [...$params]); // Is the response object an array, xml, json...?
```

**Comment by nedwors** [comment]
> What is the format of the response from a basic soap request? 
> 
> 
> 
> ```php
> 
>     $response = Soap::to('url')->call('method', [...$params]); // Is the response object an array, xml, json...?
> 
> ```

Hi @agnulakmirak, the response is a Response object from this package. You can see further by source diving here: src/Request/SoapClientRequest.php (see line 35)

Thanks
