### ISSUE TITLE
Solution: SSL - Parsing WSDL: Couldn't load from ... failed to load external entity

### ISSUE THREAD

**Issue by supermavster** [Ricorocks-Digital-Agency/Soap#51]
Hi,

If your service SOAP WSLD show this error:

```
SOAP-ERROR: Parsing WSDL: Couldn't load from '<MY_SOAP_URL> : failed to load external entity "<MY_SOAP_URL>"
```

Don't worry is normal IF You don't configure or renew the SSL (https) for the domain or ip.

In base of the answer:

> There is a difference between soap headers and HTTP headers.
> In this case you are trying to set SOAP headers.
>
> You could try to add the header by using  a `stream_context` through the `SoapClient`'s `$options`.
> See https://www.php.net/manual/en/context.http.php
> But I think that context is not being used by the SoapClient for fetching the WSDL.
>
> Leaving you with the option to either download the file(s) locally or fetch it dynamically (with curl or a stream wrapper).

_Originally posted by @veewee in https://github.com/Ricorocks-Digital-Agency/Soap/issues/38#issuecomment-880898153_

To fix this problem you only need to do it this:

```php
// Libraries
use GuzzleHttp\RedirectMiddleware;
use RicorocksDigitalAgency\Soap\Facades\Soap;

// Vars
$urlWSDL = '';
$method = '';
$params = [];

// SSL Configuration (SSL: Off)
$context = stream_context_create([
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    ]
]);

$client = Soap::to($urlWSDL)
    ->withOptions([
        // Complement (Optional)
        'allow_redirects' => RedirectMiddleware::$defaultSettings,
        'http_errors' => true,
        'decode_content' => true,
        'verify' => false,
        'cookies' => false,
        'idn_conversion' => false,
        // SSL Configuration
        'stream_context' => $context,
    ])
    ->call($method, $params);
```

And now only need try again :D 🚀 

_**Note:** In Curl the same process is with the flag `-k` for more information._

**Comment by nedwors** [comment]
Thank you for this information @supermavster

If you had time to submit an update to the docs for this solution in a troubleshooting section, that would be great. If not, no worries!
