### ISSUE TITLE
Soap fault - looks like we got no XML document

### ISSUE THREAD

**Issue by jonathan-identitech** [Ricorocks-Digital-Agency/Soap#52]
I'm getting a soap fault when making a soap request. The error message is "looks like we got no XML document". I'm making the request to a third party API so I can't debug that side, however calling other methods on the same API works fine. I am a Laravel developer with minimal experience in SOAP APIs. Please could you tell me if you have any known bugs that could account for this error? There is no additional information given in the exception being thrown and soap errors are notoriously generic. I don't know where to start in debugging this error. Any help would be greatly appreciated.

**Comment by zpwparsons** [comment]
I'm stuck with the same error. Did you manage to get it working?

**Comment by veewee** [comment]
It's a problem at the HTTP level in the internals of PHP's SoapClient. (could be e.g. lack of chunked transfer encoding transport e.g.)
The only way to get around it, is by using a better HTTP client, like e.g. guzzle - which will also give you a better exception on what went wrong *exactly*.
This is currently not possible in this package. See #35

**Comment by nedwors** [comment]
Thanks for the discussion here. Appreciate the feedback and insights.

We will be looking at upgrading the engine as mentioned to allow for this update.
