### ISSUE TITLE
Deal with the soap response as xml

### ISSUE THREAD

**Issue by ayindemalik** [Ricorocks-Digital-Agency/Soap#63]
Hi there,
please help me, when i use this package to call soap API to return  a response as XML data.
example  as follow:
$response = Soap::to('myapiservicepoint.asmx?WSDL')
    ->call('method_name');

How when I tried to convert this response to string like this simplexml_load_string((string)$customers) so that I could use it as json it give  me an error

please help

**Comment by gerfalcao** [comment]
Hello, can you share the $response data you receive?

**Comment by nedwors** [comment]
Hi @ayindemalik, 

I'm going to close this now pending the information @gerfalcao requested.

Please reopen as needed.
