### ISSUE TITLE
Examples for arrays and nodes with just values and omitted values (wsdl)

### ISSUE THREAD

**Issue by IceEcold1** [Ricorocks-Digital-Agency/Soap#65]
Hi there,

I'm trying to create a node with attributes and just a value as body.

Like this
`<Test a="b">
123
</Test>
`

I'm getting pretty far with the following code:
`$testNode = soap_node(["a" => "b"])->body([$value]);`

However when I'm sending my request to my endpoint the value is omitted. 

`<Test a="b"/>`

First off, it might be nice to have a XML debug function before we send the message that just outputs the raw XML. It's hard to determine if my endpoint omits the value or the package.

Second off, is it even possible to just use a value as body?
If so, how should the code be formatted?

**Comment by IceEcold1** [comment]
Update: fixed it. The docs are pretty unclear in terms of adding just a value and multiple nodes as array. 

For anyone still using the package, here are some examples:

To add multiple of the same nodes use a nested array.
```
$array = ["Testnode" => [0 => ["Testbody" => 1], [1 => ["Testbody" => 2]]]
```
Leads to:
```
<Testnode>
    <Testbody>1</Testbody>
</Testnode>
<Testnode>
    <Testbody>2</Testbody>
</Testnode>
```
It's also possible to add nodes with attributes this way, just change the values 1 and 2 to soap_node() functions.

To add just a value to a node with attributes the following code works:
```
$node['Testnode'] = soap_node(["attribute" => "test", "attribute2" => "test2"])->body(["_" => 123])
```
Leads to:
```
<Testnode attribute="test" attribute2="test2">123</Testnode>

In the case values are omitted from the request XML and you're sending it to a wsdl, make sure the spelling etc is correct. Not sure but I think the package removes values when they're not in the wsdl (correct me if I'm wrong).

**Comment by nedwors** [comment]
Hi @IceEcold1 

Thanks for the issue and also leaving the solution for future travellers!

If you have capacity to raise a PR to the docs to improve, that would be swell.

Thanks!
