### ISSUE TITLE
Laravel 11 

### ISSUE THREAD

**Issue by dlabsnl** [Ricorocks-Digital-Agency/Soap#69]
Hello

with the laravel 11 i get this error message could you please fix it?

Problem 1
    - Root composer.json requires laravel/framework ^11.0.6 -> satisfiable by laravel/framework[v11.0.6].
    - ricorocks-digital-agency/soap v1.7.0 requires illuminate/support ^8.16|^9.0|^10.0 -> satisfiable by illuminate/support[v8.16.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.3].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.3, v11.0.0, ..., v11.0.6], laravel/framework[v11.0.6]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires ricorocks-digital-agency/soap ^1.7 -> satisfiable by ricorocks-digital-agency/soap[v1.7.0].

**Comment by teqbylyte** [comment]
@dlabsnl Have you been able to get past this?

**Comment by razvan-p** [comment]
Similar issue here after updating to Laravel 11

```
Problem 1
    - ricorocks-digital-agency/soap[0.0.1, ..., 0.6.0, 1.0.0, ..., v1.5.0] require illuminate/support ^8.16 -> found illuminate/support[v8.16.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - ricorocks-digital-agency/soap v1.6.0 requires illuminate/support ^8.16|^9.0 -> found illuminate/support[v8.16.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - ricorocks-digital-agency/soap v1.7.0 requires illuminate/support ^8.16|^9.0|^10.0 -> found illuminate/support[v8.16.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires ricorocks-digital-agency/soap * -> satisfiable by ricorocks-digital-agency/soap[0.0.1, ..., 0.6.0, 1.0.0, ..., v1.7.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require ricorocks-digital-agency/soap:*" to figure out if any version is installable, or "composer require ricorocks-digital-agency/soap:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by nedwors** [comment]
Apologies for the delay - SOAP 2.0.0 is now released with Laravel 11 support 👍
